# - Try to find PhysX binary SDK
# - Sets PHYSXSDK_LIBS_DEBUG, PHYSXSDK_LIBS_RELEASE, PHYSXSDK_LIBS_CHECKED, PHYSXSDK_LIBS_PROFILE - lists of the libraries found
# - Sets PHYSXSDK_INCLUDE_DIRS 
# - Sets PHYSXSDK_DLLS - List of the DLLs to copy to the bin directory of projects that depend on this

include(FindPackageHandleStandardArgs)

MESSAGE("Looking for PhysXSDK ${PhysXSDK_FIND_VERSION} Cached path: ${PHYSXSDK_PATH}")
find_path(PHYSXSDK_PATH Include/PxActor.h
	PATHS
	$ENV{PM_PhysX_PATH}
	$ENV{PM_PhysX_PATH}/physx
	${GW_DEPS_ROOT}/$ENV{PM_PhysX_NAME}/${PhysXSDK_FIND_VERSION}
	${GW_DEPS_ROOT}/PhysX/${PhysXSDK_FIND_VERSION}
)

# Is the config defined in the names of binaries or path
option(PHYSX_DEPS_WITH_CONFIG_NAME "Assume that Physx dependencies contain config in their names" OFF)

if(PHYSX_DEPS_WITH_CONFIG_NAME)
	SET(DEBUG_CONFIG_SUFFIX "DEBUG")
	SET(PROFILE_CONFIG_SUFFIX "PROFILE")
	SET(CHECKED_CONFIG_SUFFIX "CHECKED")
	SET(RELEASE_CONFIG_SUFFIX "")
else()
	SET(DEBUG_CONFIG_PATH_SUFFIX "debug")
	SET(PROFILE_CONFIG_PATH_SUFFIX "profile")
	SET(CHECKED_CONFIG_PATH_SUFFIX "checked")
	SET(RELEASE_CONFIG_PATH_SUFFIX "release")
endif()

if (TARGET_BUILD_PLATFORM STREQUAL "Windows")
	# If the project pulling in this dependency needs the static crt, then append that to the path.
	if (STATIC_WINCRT)
		SET(PHYSX_CRT_SUFFIX "-staticcrt")
	else()
		SET(PHYSX_CRT_SUFFIX "")
	endif()

	if (CMAKE_CL_64)
		SET(PHYSX_ARCH_FOLDER "win64")
		SET(PHYSX_ARCH_FILE "_64")
	else()
		SET(PHYSX_ARCH_FOLDER "win32")
		SET(PHYSX_ARCH_FILE "_x86")
	endif()

	# What compiler version do we want?

	if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 18.0.0.0 AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19.0.0.0)
		SET(VS_STR "VS2013")
	elseif (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 19.0.0.0 AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19.10.0.0)
		SET(VS_STR "VS2015")
	elseif(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 19.10.0.0)
		SET(VS_STR "VS2017")
	else()
		MESSAGE(FATAL_ERROR "Failed to find compatible PxSharedSDK - Only supporting VS2013 and VS2015")
	endif()
		
	SET(LIB_PATH ${PHYSXSDK_PATH}/lib/${VS_STR}${PHYSX_ARCH_FOLDER}-cmake${PHYSX_CRT_SUFFIX} ${PHYSXSDK_PATH}/lib/${VS_STR}${PHYSX_ARCH_FOLDER} ${PHYSXSDK_PATH}/../Lib/${PHYSX_ARCH_FOLDER}/${VS_STR} ${PHYSXSDK_PATH}/../Lib)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll")

elseif(TARGET_BUILD_PLATFORM STREQUAL "PS4")
	SET(LIB_PATH ${PHYSXSDK_PATH}/lib/vc14ps4-cmake ${PHYSXSDK_PATH}/../Lib)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
	SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
elseif(TARGET_BUILD_PLATFORM STREQUAL "XboxOne")
	SET(LIB_PATH ${PHYSXSDK_PATH}/lib/vc14xboxone-cmake ${PHYSXSDK_PATH}/../lib)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a" ".lib")
	SET(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
elseif(TARGET_BUILD_PLATFORM STREQUAL "linux")
	SET(LIB_PATH ${PHYSXSDK_PATH}/lib/linux64-cmake ${PHYSXSDK_PATH}/../Lib)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
	SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
	SET(PHYSX_ARCH_FILE "_x64")
endif()

# Now find all of the PhysX libs in the lib directory

find_library(PHYSX_LIB
	NAMES PHYSX${RELEASE_CONFIG_SUFFIX} PHYSX${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXEXTENSIONS_STATIC_LIB
	NAMES PhysXExtensions_static${RELEASE_CONFIG_SUFFIX} PhysXExtensions_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB
	NAMES PhysXCharacterKinematic_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOMMON_LIB
	NAMES PHYSXCommon${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOOKING_LIB
	NAMES PHYSXCooking${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVEL_STATIC_LIB
	NAMES LowLevel_static${RELEASE_CONFIG_SUFFIX} LowLevel_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELAABB_STATIC_LIB
	NAMES LowLevelAABB_static${RELEASE_CONFIG_SUFFIX} LowLevelAABB_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELDYNAMICS_STATIC_LIB
	NAMES LowLevelDynamics_static${RELEASE_CONFIG_SUFFIX} LowLevelDynamics_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(SCENEQUERY_STATIC_LIB
	NAMES SceneQuery_static${RELEASE_CONFIG_SUFFIX} SceneQuery_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)
find_library(SIMULATIONCONTROLLER_STATIC_LIB
	NAMES SimulationController_static${RELEASE_CONFIG_SUFFIX} SimulationController_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
)

find_library(PHYSX_LIB_DEBUG
	NAMES PHYSX${DEBUG_CONFIG_SUFFIX} PHYSX${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXEXTENSIONS_STATIC_LIB_DEBUG
	NAMES PhysXExtensions_static${DEBUG_CONFIG_SUFFIX} PhysXExtensions_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB_DEBUG
	NAMES PhysXCharacterKinematic_static${DEBUG_CONFIG_SUFFIX} PhysXCharacterKinematic_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOMMON_LIB_DEBUG
	NAMES PHYSXCommon${DEBUG_CONFIG_SUFFIX} PHYSXCommon${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOOKING_LIB_DEBUG
	NAMES PHYSXCooking${DEBUG_CONFIG_SUFFIX} PHYSXCooking${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVEL_STATIC_LIB_DEBUG
	NAMES LowLevel_static${DEBUG_CONFIG_SUFFIX} LowLevel_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELAABB_STATIC_LIB_DEBUG
	NAMES LowLevelAABB_static${DEBUG_CONFIG_SUFFIX} LowLevelAABB_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELDYNAMICS_STATIC_LIB_DEBUG
	NAMES LowLevelDynamics_static${DEBUG_CONFIG_SUFFIX} LowLevelDynamics_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(SCENEQUERY_STATIC_LIB_DEBUG
	NAMES SceneQuery_static${DEBUG_CONFIG_SUFFIX} SceneQuery_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)
find_library(SIMULATIONCONTROLLER_STATIC_LIB_DEBUG
	NAMES SimulationController_static${DEBUG_CONFIG_SUFFIX} SimulationController_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
)

find_library(PHYSX_LIB_CHECKED
	NAMES PHYSX${CHECKED_CONFIG_SUFFIX} PHYSX${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXEXTENSIONS_STATIC_LIB_CHECKED
	NAMES PhysXExtensions_static${CHECKED_CONFIG_SUFFIX} PhysXExtensions_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB_CHECKED
	NAMES PhysXCharacterKinematic_static${CHECKED_CONFIG_SUFFIX} PhysXCharacterKinematic_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOMMON_LIB_CHECKED
	NAMES PHYSXCommon${CHECKED_CONFIG_SUFFIX} PHYSXCommon${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOOKING_LIB_CHECKED
	NAMES PHYSXCooking${CHECKED_CONFIG_SUFFIX} PHYSXCooking${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVEL_STATIC_LIB_CHECKED
	NAMES LowLevel_static${CHECKED_CONFIG_SUFFIX} LowLevel_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELAABB_STATIC_LIB_CHECKED
	NAMES LowLevelAABB_static${CHECKED_CONFIG_SUFFIX} LowLevelAABB_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELDYNAMICS_STATIC_LIB_CHECKED
	NAMES LowLevelDynamics_static${CHECKED_CONFIG_SUFFIX} LowLevelDynamics_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(SCENEQUERY_STATIC_LIB_CHECKED
	NAMES SceneQuery_static${CHECKED_CONFIG_SUFFIX} SceneQuery_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)
find_library(SIMULATIONCONTROLLER_STATIC_LIB_CHECKED
	NAMES SimulationController_static${CHECKED_CONFIG_SUFFIX} SimulationController_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
)

find_library(PHYSX_LIB_PROFILE
	NAMES PHYSX${PROFILE_CONFIG_SUFFIX} PHYSX${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXEXTENSIONS_STATIC_LIB_PROFILE
	NAMES PhysXExtensions_static${PROFILE_CONFIG_SUFFIX} PhysXExtensions_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB_PROFILE
	NAMES PhysXCharacterKinematic_static${PROFILE_CONFIG_SUFFIX} PhysXCharacterKinematic_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOMMON_LIB_PROFILE
	NAMES PHYSXCommon${PROFILE_CONFIG_SUFFIX} PHYSXCommon${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(PHYSXCOOKING_LIB_PROFILE
	NAMES PHYSXCooking${PROFILE_CONFIG_SUFFIX} PHYSXCooking${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVEL_STATIC_LIB_PROFILE
	NAMES LowLevel_static${PROFILE_CONFIG_SUFFIX} LowLevel_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELAABB_STATIC_LIB_PROFILE
	NAMES LowLevelAABB_static${PROFILE_CONFIG_SUFFIX} LowLevelAABB_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(LOWLEVELDYNAMICS_STATIC_LIB_PROFILE
	NAMES LowLevelDynamics_static${PROFILE_CONFIG_SUFFIX} LowLevelDynamics_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(SCENEQUERY_STATIC_LIB_PROFILE
	NAMES SceneQuery_static${PROFILE_CONFIG_SUFFIX} SceneQuery_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)
find_library(SIMULATIONCONTROLLER_STATIC_LIB_PROFILE
	NAMES SimulationController_static${PROFILE_CONFIG_SUFFIX} SimulationController_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
	PATHS ${LIB_PATH}
	PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
)

if (TARGET_BUILD_PLATFORM STREQUAL "Windows")

	find_library(PHYSXGPU_LIB
		NAMES PHYSXGpu${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${LIB_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXGPU_LIB_DEBUG
		NAMES PHYSXGpu${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${LIB_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
	)


	SET(DLL_PATH ${PHYSXSDK_PATH}/bin/${VS_STR}${PHYSX_ARCH_FOLDER}-cmake${PHYSX_CRT_SUFFIX} ${PHYSXSDK_PATH}/bin/${VS_STR}${PHYSX_ARCH_FOLDER} ${PHYSXSDK_PATH}/../Bin/${PHYSX_ARCH_FOLDER}/${VS_STR} ${PHYSXSDK_PATH}/../Bin)

	find_library(PHYSX_DLL
		NAMES PHYSX${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOMMON_DLL
		NAMES PHYSXCommon${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOOKING_DLL
		NAMES PHYSXCooking${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXGPU_DLL
		NAMES PHYSXGpu${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
	)

	
	find_library(PHYSX_DLL_DEBUG
		NAMES PHYSX${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOMMON_DLL_DEBUG
		NAMES PHYSXCommon${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOOKING_DLL_DEBUG
		NAMES PHYSXCooking${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
	)
	# NOTE - GPU dlls not included in required dlls or libs as they're optional.
	find_library(PHYSXGPU_DLL_DEBUG
		NAMES PHYSXGpu${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
	)
	
	find_library(PHYSX_DLL_PROFILE
		NAMES PHYSX${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOMMON_DLL_PROFILE
		NAMES PHYSXCommon${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOOKING_DLL_PROFILE
		NAMES PHYSXCooking${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
	)
	# NOTE - GPU dlls not included in required dlls or libs as they're optional.
	find_library(PHYSXGPU_DLL_PROFILE
		NAMES PHYSXGpu${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
	)
	
	find_library(PHYSX_DLL_CHECKED
		NAMES PHYSX${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOMMON_DLL_CHECKED
		NAMES PHYSXCommon${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
	)
	find_library(PHYSXCOOKING_DLL_CHECKED
		NAMES PHYSXCooking${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
	)
	# NOTE - GPU dlls not included in required dlls or libs as they're optional.
	find_library(PHYSXGPU_DLL_CHECKED
		NAMES PHYSXGpu${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${DLL_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
	)
	
	# Create this list to check for found dlls below
	SET(DLL_VAR_LIST 
		PHYSX_DLL 
		PHYSXCOMMON_DLL
		PHYSXCOOKING_DLL 

		PHYSX_DLL_DEBUG 
		PHYSXCOMMON_DLL_DEBUG
		PHYSXCOOKING_DLL_DEBUG

		PHYSX_DLL_PROFILE 
		PHYSXCOMMON_DLL_PROFILE
		PHYSXCOOKING_DLL_PROFILE

		PHYSX_DLL_CHECKED 
		PHYSXCOMMON_DLL_CHECKED
		PHYSXCOOKING_DLL_CHECKED
	)
endif()

if (TARGET_BUILD_PLATFORM STREQUAL "linux")
	SET(BIN_PATH ${PHYSXSDK_PATH}/bin/linux64-cmake ${PHYSXSDK_PATH}/../Bin)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so")

    find_library(PHYSX_LIB
        NAMES PHYSX${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOOKING_LIB
        NAMES PHYSXCooking${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB
        NAMES PhysXCharacterKinematic_static${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOMMON_LIB
        NAMES PHYSXCommon${RELEASE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${RELEASE_CONFIG_PATH_SUFFIX}
    )

    find_library(PHYSX_LIB_DEBUG
        NAMES PHYSX${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOOKING_LIB_DEBUG
        NAMES PHYSXCooking${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB_DEBUG
        NAMES PhysXCharacterKinematic_static${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOMMON_LIB_DEBUG
        NAMES PHYSXCommon${DEBUG_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${DEBUG_CONFIG_PATH_SUFFIX}
    )

    find_library(PHYSX_LIB_CHECKED
        NAMES PHYSX${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOOKING_LIB_CHECKED
        NAMES PHYSXCooking${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB_CHECKED
        NAMES PhysXCharacterKinematic_static${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOMMON_LIB_CHECKED
        NAMES PHYSXCommon${CHECKED_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${CHECKED_CONFIG_PATH_SUFFIX}
    )
    
    find_library(PHYSX_LIB_PROFILE
        NAMES PHYSX${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOOKING_LIB_PROFILE
        NAMES PHYSXCooking${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCHARACTERKINEMATIC_STATIC_LIB_PROFILE
        NAMES PhysXCharacterKinematic_static${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
    )
    find_library(PHYSXCOMMON_LIB_PROFILE
        NAMES PHYSXCommon${PROFILE_CONFIG_SUFFIX}${PHYSX_ARCH_FILE}
		PATHS ${BIN_PATH}
		PATH_SUFFIXES ${PROFILE_CONFIG_PATH_SUFFIX}
    )
endif()


FIND_PACKAGE_HANDLE_STANDARD_ARGS(PHYSXSDK
	DEFAULT_MSG
	PHYSXSDK_PATH
	
	PHYSX_LIB
	PHYSXEXTENSIONS_STATIC_LIB
	PHYSXCHARACTERKINEMATIC_STATIC_LIB
	PHYSXCOMMON_LIB
	PHYSXCOOKING_LIB
	LOWLEVEL_STATIC_LIB
	LOWLEVELAABB_STATIC_LIB
	LOWLEVELDYNAMICS_STATIC_LIB
	SCENEQUERY_STATIC_LIB
	SIMULATIONCONTROLLER_STATIC_LIB

	PHYSX_LIB_DEBUG
	PHYSXEXTENSIONS_STATIC_LIB_DEBUG
	PHYSXCHARACTERKINEMATIC_STATIC_LIB_DEBUG
	PHYSXCOMMON_LIB_DEBUG
	PHYSXCOOKING_LIB_DEBUG
	LOWLEVEL_STATIC_LIB_DEBUG
	LOWLEVELAABB_STATIC_LIB_DEBUG
	LOWLEVELDYNAMICS_STATIC_LIB_DEBUG
	SCENEQUERY_STATIC_LIB_DEBUG
	SIMULATIONCONTROLLER_STATIC_LIB_DEBUG

	PHYSX_LIB_CHECKED
	PHYSXEXTENSIONS_STATIC_LIB_CHECKED
	PHYSXCHARACTERKINEMATIC_STATIC_LIB_CHECKED
	PHYSXCOMMON_LIB_CHECKED
	PHYSXCOOKING_LIB_CHECKED
	LOWLEVEL_STATIC_LIB_CHECKED
	LOWLEVELAABB_STATIC_LIB_CHECKED
	LOWLEVELDYNAMICS_STATIC_LIB_CHECKED
	SCENEQUERY_STATIC_LIB_CHECKED
	SIMULATIONCONTROLLER_STATIC_LIB_CHECKED

	PHYSX_LIB_PROFILE
	PHYSXEXTENSIONS_STATIC_LIB_PROFILE
	PHYSXCHARACTERKINEMATIC_STATIC_LIB_PROFILE
	PHYSXCOMMON_LIB_PROFILE
	PHYSXCOOKING_LIB_PROFILE
	LOWLEVEL_STATIC_LIB_PROFILE
	LOWLEVELAABB_STATIC_LIB_PROFILE
	LOWLEVELDYNAMICS_STATIC_LIB_PROFILE
	SCENEQUERY_STATIC_LIB_PROFILE
	SIMULATIONCONTROLLER_STATIC_LIB_PROFILE
	
	${DLL_VAR_LIST}
)

if (PHYSXSDK_FOUND)
	
	SET(PHYSXSDK_INCLUDE_DIRS
		${PHYSXSDK_PATH}/Include
		${PHYSXSDK_PATH}/Include/characterdynamic
		${PHYSXSDK_PATH}/Include/characterkinematic
		${PHYSXSDK_PATH}/Include/common 
		${PHYSXSDK_PATH}/Include/cooking
		${PHYSXSDK_PATH}/Include/deformable
		${PHYSXSDK_PATH}/Include/extensions 
		${PHYSXSDK_PATH}/Include/filebuf
		${PHYSXSDK_PATH}/Include/foundation
		${PHYSXSDK_PATH}/Include/geometry
		${PHYSXSDK_PATH}/Include/gpu
		${PHYSXSDK_PATH}/Include/particles
		${PHYSXSDK_PATH}/Include/pvd
		${PHYSXSDK_PATH}/Include/task
		${PHYSXSDK_PATH}/Include/vehicle
		${PHYSXSDK_PATH}/source/fastxml/include
		${PHYSXSDK_PATH}/source/filebuf/include
		${PHYSXSDK_PATH}/source/foundation/include
	)
	
	SET(PHYSXSDK_LIBS_RELEASE ${PHYSX_LIB} ${PHYSXEXTENSIONS_STATIC_LIB} ${PHYSXCHARACTERKINEMATIC_STATIC_LIB} ${PHYSXCOMMON_LIB} ${PHYSXCOOKING_LIB} ${PHYSXGPU_LIB} ${LOWLEVEL_STATIC_LIB} ${LOWLEVELAABB_STATIC_LIB} ${LOWLEVELDYNAMICS_STATIC_LIB} ${SCENEQUERY_STATIC_LIB} ${SIMULATIONCONTROLLER_STATIC_LIB}
		CACHE STRING ""
	)
	SET(PHYSXSDK_LIBS_DEBUG ${PHYSX_LIB_DEBUG} ${PHYSXEXTENSIONS_STATIC_LIB_DEBUG} ${PHYSXCHARACTERKINEMATIC_STATIC_LIB_DEBUG} ${PHYSXCOMMON_LIB_DEBUG} ${PHYSXCOOKING_LIB_DEBUG} ${PHYSXGPU_LIB_DEBUG} ${LOWLEVEL_STATIC_LIB_DEBUG} ${LOWLEVELAABB_STATIC_LIB_DEBUG} ${LOWLEVELDYNAMICS_STATIC_LIB_DEBUG} ${SCENEQUERY_STATIC_LIB_DEBUG} ${SIMULATIONCONTROLLER_STATIC_LIB_DEBUG}
		CACHE STRING ""
	)
	SET(PHYSXSDK_LIBS_CHECKED ${PHYSX_LIB_CHECKED} ${PHYSXEXTENSIONS_STATIC_LIB_CHECKED} ${PHYSXCHARACTERKINEMATIC_STATIC_LIB_CHECKED} ${PHYSXCOMMON_LIB_CHECKED} ${PHYSXCOOKING_LIB_CHECKED} ${PHYSXGPU_LIB_CHECKED} ${LOWLEVEL_STATIC_LIB_CHECKED} ${LOWLEVELAABB_STATIC_LIB_CHECKED} ${LOWLEVELDYNAMICS_STATIC_LIB_CHECKED} ${SCENEQUERY_STATIC_LIB_CHECKED} ${SIMULATIONCONTROLLER_STATIC_LIB_CHECKED}
		CACHE STRING ""
	)
	SET(PHYSXSDK_LIBS_PROFILE ${PHYSX_LIB_PROFILE} ${PHYSXEXTENSIONS_STATIC_LIB_PROFILE} ${PHYSXCHARACTERKINEMATIC_STATIC_LIB_PROFILE} ${PHYSXCOMMON_LIB_PROFILE} ${PHYSXCOOKING_LIB_PROFILE} ${PHYSXGPU_LIB_PROFILE} ${LOWLEVEL_STATIC_LIB_PROFILE} ${LOWLEVELAABB_STATIC_LIB_PROFILE} ${LOWLEVELDYNAMICS_STATIC_LIB_PROFILE} ${SCENEQUERY_STATIC_LIB_PROFILE} ${SIMULATIONCONTROLLER_STATIC_LIB_PROFILE}
		CACHE STRING ""
	)

	#NOTE: This is all dll configs, might need to be split.
	SET(PHYSXSDK_DLLS 
		${PHYSX_DLL} ${PHYSXCHARACTERKINEMATIC_DLL} ${PHYSXCOMMON_DLL} ${PHYSXCOOKING_DLL} ${PHYSXGPU_DLL} 
		${PHYSX_DLL_DEBUG} ${PHYSXCHARACTERKINEMATIC_DLL_DEBUG} ${PHYSXCOMMON_DLL_DEBUG} ${PHYSXCOOKING_DLL_DEBUG} ${PHYSXGPU_DLL_DEBUG} 
		${PHYSX_DLL_PROFILE} ${PHYSXCHARACTERKINEMATIC_DLL_PROFILE} ${PHYSXCOMMON_DLL_PROFILE} ${PHYSXCOOKING_DLL_PROFILE} ${PHYSXGPU_DLL_PROFILE} 
		${PHYSX_DLL_CHECKED} ${PHYSXCHARACTERKINEMATIC_DLL_CHECKED} ${PHYSXCOMMON_DLL_CHECKED} ${PHYSXCOOKING_DLL_CHECKED} ${PHYSXGPU_DLL_CHECKED} 
	)
	
	SET(PHYSXSDK_LIBRARIES "" CACHE STRING "")
	
	foreach(x ${PHYSXSDK_LIBS_RELEASE})
		list(APPEND PHYSXSDK_LIBRARIES optimized ${x})
	endforeach()
	
	foreach(x ${PHYSXSDK_LIBS_DEBUG})
		list(APPEND PHYSXSDK_LIBRARIES debug ${x})
	endforeach()
endif()
