#ifdef PLUGINBT_LIB
# define PLUGINBT_EXPORT Q_DECL_EXPORT
#else
# define PLUGINBT_EXPORT Q_DECL_IMPORT
#endif

#ifdef PLUGINBTRENDER_LIB
# define PLUGINBTRENDER_EXPORT Q_DECL_EXPORT
#else
# define PLUGINBTRENDER_EXPORT Q_DECL_IMPORT
#endif