#
# Build NvBlastExtSerialization Linux
#

SET(BLASTEXTSERIALIZATION_PLATFORM_COMMON_FILES
)

SET(BLASTEXTSERIALIZATION_PLATFORM_INCLUDES
)

SET(BLASTEXTSERIALIZATION_COMPILE_DEFS
	# Common to all configurations
	${BLAST_SLN_COMPILE_DEFS};
	
	$<$<CONFIG:debug>:${BLAST_SLN_DEBUG_COMPILE_DEFS}>
	$<$<CONFIG:checked>:${BLAST_SLN_CHECKED_COMPILE_DEFS}>
	$<$<CONFIG:profile>:${BLAST_SLN_PROFILE_COMPILE_DEFS}>
	$<$<CONFIG:release>:${BLAST_SLN_RELEASE_COMPILE_DEFS}>
)

SET(BLASTEXTSERIALIZATION_LIB_TYPE SHARED)

IF (NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
	SET(BLASTEXTSERIALIZATION_COMPILE_OPTIONS "-Wno-sign-compare")
ELSE()
	SET(BLASTEXTSERIALIZATION_COMPILE_OPTIONS "-Wno-sign-compare" "-Wno-unused-parameter" "-Wno-return-type-c-linkage")
ENDIF()
