@ECHO OFF
rem SET SCRIPT_PATH=%CD%
rem cd %SCRIPT_PATH%

echo set ENV variables ...
rem SETLOCAL

SET PM_DRIVE=%CD:~0,2%
SET PM_PACKAGES_ROOT=%PM_DRIVE%\NVIDIA\packman-repo
echo PM_PACKAGES_ROOT is %PM_PACKAGES_ROOT%

REM Get the absolute path for \trunk\
@pushd ..\..\..\..
SET SRC_ROOT=%CD%
@popd
echo SRC_ROOT is %SRC_ROOT%

IF %SRC_ROOT%Nothing==Nothing EXIT /B 1

SET BLAST_PATH=%SRC_ROOT%
SET EXTERNAL_ROOT=%SRC_ROOT%\..\..\external
SET NVCOMMON_ROOT=%SRC_ROOT%\..\..\external
SET PX_VERSION=1.0.21652946
SET PHYSX_VERSION=3.4.21652946
SET APEX_VERSION=1.4.21652946
SET IMGUI_PATH=%PM_PACKAGES_ROOT%\imgui\1.49
SET TINYOBJ_PATH=%PM_PACKAGES_ROOT%\tinyObjLoader\1.0
SET TCLAP_PATH=%PM_PACKAGES_ROOT%\tclap\1.2.1
SET FBXSDK_ROOT=%PM_PACKAGES_ROOT%\FBXSDK\2017.0.1
SET NVTOOLSEXT=%PM_PACKAGES_ROOT%\nvToolsExt\1.0
SET DIRECTXTEX_PATH=%PM_PACKAGES_ROOT%\DirectXTex\10.5.2016.2
SET DXUT_PATH=%PM_PACKAGES_ROOT%\DXUT\9.15.2016.1
SET SHADOWLIB_PATH=%PM_PACKAGES_ROOT%\shadow_lib\2.1.20145239
SET HBAOPLUS_PATH=%PM_PACKAGES_ROOT%\hbao_plus\3.0.20515708

SET D3D11_ROOT=%EXTERNAL_ROOT%\D3D11
SET NvFoundation_ROOT=%EXTERNAL_ROOT%\NvFoundation\1.1\trunk
SET NsFoundation_ROOT=%EXTERNAL_ROOT%\NsFoundation\1.1\trunk
SET NvParameterized_ROOT=%EXTERNAL_ROOT%\NvParameterized\1.1\trunk
SET NsFileBuffer_ROOT=%EXTERNAL_ROOT%\NsFileBuffer\1.1\trunk
SET NsFastXML_ROOT=%EXTERNAL_ROOT%\NsFastXML\1.1\trunk
SET OpenAutomate_ROOT=%EXTERNAL_ROOT%\OpenAutomate-1.0-7
SET SDL_ROOT=%EXTERNAL_ROOT%\SDL2-2.0.0
set XPJ="%SRC_ROOT%\tools\ArtistTools\project\script\xpj4.exe"

SET QTDIR=%EXTERNAL_ROOT%\Qt5.6.1\vc2015
SET FBXSDK_LIB_ROOT=%FBXSDK_ROOT%\lib\vs2015
set VC_VERSION=vc14
set VS_STRING=VS2015

SET PX_SHARED=%PM_PACKAGES_ROOT%\PxShared-%VC_VERSION%win32\%PX_VERSION%
SET PHYSX_PATH=%PM_PACKAGES_ROOT%\PhysX-%VC_VERSION%win32\%PHYSX_VERSION%
SET APEX_PATH=%PM_PACKAGES_ROOT%\Apex-%VC_VERSION%win32\%APEX_VERSION%
%XPJ% -v 4 -t %VC_VERSION% -p win32 -x ArtistTools.xml

SET PX_SHARED=%PM_PACKAGES_ROOT%\PxShared-%VC_VERSION%win64\%PX_VERSION%
SET PHYSX_PATH=%PM_PACKAGES_ROOT%\PhysX-%VC_VERSION%win64\%PHYSX_VERSION%
SET APEX_PATH=%PM_PACKAGES_ROOT%\Apex-%VC_VERSION%win64\%APEX_VERSION%
%XPJ% -v 4 -t %VC_VERSION% -p win64 -x ArtistTools.xml

SET QTDIR=%EXTERNAL_ROOT%\Qt5.6.1\vc2013
SET FBXSDK_LIB_ROOT=%FBXSDK_ROOT%\lib\vs2013
SET VC_VERSION=vc12
SET VS_STRING=VS2013

SET PX_SHARED=%PM_PACKAGES_ROOT%\PxShared-%VC_VERSION%win32\%PX_VERSION%
SET PHYSX_PATH=%PM_PACKAGES_ROOT%\PhysX-%VC_VERSION%win32\%PHYSX_VERSION%
SET APEX_PATH=%PM_PACKAGES_ROOT%\Apex-%VC_VERSION%win32\%APEX_VERSION%
%XPJ% -v 4 -t %VC_VERSION% -p win32 -x ArtistTools.xml

SET PX_SHARED=%PM_PACKAGES_ROOT%\PxShared-%VC_VERSION%win64\%PX_VERSION%
SET PHYSX_PATH=%PM_PACKAGES_ROOT%\PhysX-%VC_VERSION%win64\%PHYSX_VERSION%
SET APEX_PATH=%PM_PACKAGES_ROOT%\Apex-%VC_VERSION%win64\%APEX_VERSION%
%XPJ% -v 4 -t %VC_VERSION% -p win64 -x ArtistTools.xml

echo ""
echo if the following root paths are not right. please correct them
echo SRC_ROOT is %SRC_ROOT%
echo D3D11_ROOT root is %D3D11_ROOT%
echo QTDIR root is %QTDIR%
echo FBXSDK_ROOT root is %FBXSDK_ROOT%
echo NvFoundation_ROOT root is %NvFoundation_ROOT%
echo NsFoundation_ROOT root is %NsFoundation_ROOT%
echo NvParameterized_ROOT root is %NvParameterized_ROOT%
echo OpenAutomate_ROOT root is %OpenAutomate_ROOT%
echo SDL_ROOT root is %SDL_ROOT%