#
# Build NvBlastExtPxSerialization Linux
#

SET(BLASTEXTPXSERIALIZATION_PLATFORM_COMMON_FILES
)

SET(BLASTEXTPXSERIALIZATION_PLATFORM_INCLUDES
)

SET(BLASTEXTPXSERIALIZATION_COMPILE_DEFS
	# Common to all configurations
	${BLAST_SLN_COMPILE_DEFS};
	
	$<$<CONFIG:debug>:${BLAST_SLN_DEBUG_COMPILE_DEFS}>
	$<$<CONFIG:checked>:${BLAST_SLN_CHECKED_COMPILE_DEFS}>
	$<$<CONFIG:profile>:${BLAST_SLN_PROFILE_COMPILE_DEFS}>
	$<$<CONFIG:release>:${BLAST_SLN_RELEASE_COMPILE_DEFS}>
)

SET(BLASTEXTPXSERIALIZATION_LIB_TYPE SHARED)

IF (NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
	SET(BLASTEXTPXSERIALIZATION_COMPILE_OPTIONS "-Wno-sign-compare")
ELSE()
	SET(BLASTEXTPXSERIALIZATION_COMPILE_OPTIONS "-Wno-sign-compare" "-Wno-return-type-c-linkage" "-Wno-unused-parameter")
ENDIF()


