#
# Build DataConverter common
#

SET(DATACONVERTER_SOURCE_DIR ${PROJECT_SOURCE_DIR}/DataConverter/src)

FIND_PACKAGE(tclap $ENV{PM_tclap_VERSION} REQUIRED)

# Include here after the directories are defined so that the platform specific file can use the variables.
include(${PROJECT_CMAKE_FILES_DIR}/${TARGET_BUILD_PLATFORM}/DataConverter.cmake)

SET(COMMON_FILES
	${DATACONVERTER_PLATFORM_COMMON_FILES}
	
	${DATACONVERTER_SOURCE_DIR}/Main.cpp
)

ADD_EXECUTABLE(DataConverter 
	${COMMON_FILES}
)

set_target_properties(DataConverter 
	PROPERTIES DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX}
	CHECKED_POSTFIX ${CMAKE_CHECKED_POSTFIX}
	RELEASE_POSTFIX ${CMAKE_RELEASE_POSTFIX}
	PROFILE_POSTFIX ${CMAKE_PROFILE_POSTFIX}
)


SOURCE_GROUP("src" FILES ${COMMON_FILES})

# Target specific compile options

TARGET_INCLUDE_DIRECTORIES(DataConverter 
	PRIVATE ${DATACONVERTER_PLATFORM_INCLUDES}
	PRIVATE ${BLAST_ROOT_DIR}/source/common

	PRIVATE ${TCLAP_INCLUDE_DIRS}
)

TARGET_COMPILE_DEFINITIONS(DataConverter 
	PRIVATE ${DATACONVERTER_COMPILE_DEFS}
)

SET_TARGET_PROPERTIES(DataConverter PROPERTIES 
	PDB_NAME_DEBUG "DataConverter${CMAKE_DEBUG_POSTFIX}"
	PDB_NAME_CHECKED "DataConverter${CMAKE_CHECKED_POSTFIX}"
	PDB_NAME_PROFILE "DataConverter${CMAKE_PROFILE_POSTFIX}"
	PDB_NAME_RELEASE "DataConverter${CMAKE_RELEASE_POSTFIX}"
)

# Do final direct sets after the target has been defined
TARGET_LINK_LIBRARIES(DataConverter NvBlast NvBlastExtConverterLL)


ADD_CUSTOM_COMMAND(TARGET DataConverter POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E copy_if_different 
	${PHYSXSDK_DLLS} ${PXSHAREDSDK_DLLS}
	${BL_EXE_OUTPUT_DIR}
)
