#
# Build NvBlastExt Common
#

SET(COMMON_SOURCE_DIR ${PROJECT_SOURCE_DIR}/common)

SET(AUTHORING_COMMON_EXT_SOURCE_DIR ${PROJECT_SOURCE_DIR}/extensions/authoringCommon/source)
SET(AUTHORING_COMMON_EXT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/extensions/authoringCommon/include)
SET(RT_EXT_SOURCE_DIR ${PROJECT_SOURCE_DIR}/extensions/RT/source)
SET(COMMON_EXT_SOURCE_DIR ${PROJECT_SOURCE_DIR}/extensions/common/source)
SET(RT_EXT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/extensions/RT/include)

FIND_PACKAGE(PxSharedSDK $ENV{PM_PxShared_VERSION} REQUIRED)

# Include here after the directories are defined so that the platform specific file can use the variables.
include(${PROJECT_CMAKE_FILES_DIR}/${TARGET_BUILD_PLATFORM}/NvBlastExtRT.cmake)

SET(COMMON_FILES
	${BLASTEXT_PLATFORM_COMMON_FILES}	
)

SET(PUBLIC_FILES
	${RT_EXT_INCLUDE_DIR}/NvBlastExtRT.h
	${AUTHORING_COMMON_EXT_INCLUDE_DIR}/NvBlastExtAuthoringPatternGenerator.h
	${AUTHORING_COMMON_EXT_INCLUDE_DIR}/NvBlastExtAuthoringAccelerator.h
	${AUTHORING_COMMON_EXT_INCLUDE_DIR}/NvBlastExtAuthoringMesh.h
	${AUTHORING_COMMON_EXT_INCLUDE_DIR}/NvBlastExtAuthoringTypes.h
)

SET(EXT_RT_FILES
	${RT_EXT_SOURCE_DIR}/NvBlastExtRT.cpp
	${RT_EXT_SOURCE_DIR}/NvBlastExtRTGeometry.cpp
	${RT_EXT_SOURCE_DIR}/NvBlastExtRTGeometry.h
	${RT_EXT_SOURCE_DIR}/NvBlastExtRTImpl.cpp
	${RT_EXT_SOURCE_DIR}/NvBlastExtRTImpl.h
	${RT_EXT_SOURCE_DIR}/NvBlastExtRTMultithreadedImpl.cpp
	${RT_EXT_SOURCE_DIR}/NvBlastExtRTMultithreadedImpl.h

	
	${AUTHORING_COMMON_EXT_SOURCE_DIR}/NvBlastExtAuthoringAccelerator.cpp
	${AUTHORING_COMMON_EXT_SOURCE_DIR}/NvBlastExtAuthoringMeshImpl.cpp
	${AUTHORING_COMMON_EXT_SOURCE_DIR}/NvBlastExtAuthoringMeshImpl.h
	${AUTHORING_COMMON_EXT_SOURCE_DIR}/NvBlastExtAuthoringInternalCommon.h	
)


ADD_LIBRARY(NvBlastExtRT ${BLAST_EXT_SHARED_LIB_TYPE} 
	${COMMON_FILES}
	${PUBLIC_FILES}
	${EXT_RT_FILES}
)

SOURCE_GROUP("common" FILES ${COMMON_FILES})
SOURCE_GROUP("public" FILES ${PUBLIC_FILES})
SOURCE_GROUP("src" FILES ${EXT_RT_FILES})


# Target specific compile options

TARGET_INCLUDE_DIRECTORIES(NvBlastExtRT 
	PRIVATE ${BLASTEXT_PLATFORM_INCLUDES}

	PUBLIC ${RT_EXT_INCLUDE_DIR}
	PRIVATE ${RT_EXT_SOURCE_DIR}
	
	PUBLIC ${AUTHORING_COMMON_EXT_INCLUDE_DIR}
	PRIVATE ${AUTHORING_COMMON_EXT_SOURCE_DIR}
		
	
	PRIVATE ${PROJECT_SOURCE_DIR}/common
	PRIVATE ${COMMON_EXT_SOURCE_DIR}	

	PRIVATE ${PXSHAREDSDK_INCLUDE_DIRS}
)

TARGET_COMPILE_DEFINITIONS(NvBlastExtRT
	PRIVATE ${BLASTEXT_COMPILE_DEFS}
)

# Warning disables for Capn Proto
TARGET_COMPILE_OPTIONS(NvBlastExtRT
	PRIVATE ${BLASTEXT_PLATFORM_COMPILE_OPTIONS}
)

SET_TARGET_PROPERTIES(NvBlastExtRT PROPERTIES 
	PDB_NAME_DEBUG "debug/NvBlastExtRT${CMAKE_DEBUG_POSTFIX}"
	PDB_NAME_CHECKED "checked/NvBlastExtRT${CMAKE_CHECKED_POSTFIX}"
	PDB_NAME_PROFILE "profile/NvBlastExtRT${CMAKE_PROFILE_POSTFIX}"
	PDB_NAME_RELEASE "release/NvBlastExtRT${CMAKE_RELEASE_POSTFIX}"
)

# Do final direct sets after the target has been defined
TARGET_LINK_LIBRARIES(NvBlastExtRT 
	PUBLIC NvBlast NvBlastGlobals
	PUBLIC ${BLASTEXT_PLATFORM_LINKED_LIBS}
)
