#
# Build LegacyConverter Windows
#

SET(LEGACYCONVERTER_PLATFORM_COMMON_FILES
)

SET(LEGACYCONVERTER_PLATFORM_INCLUDES
)

SET(LEGACYCONVERTER_COMPILE_DEFS
	# Common to all configurations
	${BLASTTOOLS_SLN_COMPILE_DEFS};_CONSOLE
	
	$<$<CONFIG:debug>:${BLASTTOOLS_SLN_DEBUG_COMPILE_DEFS}>
	$<$<CONFIG:checked>:${BLASTTOOLS_SLN_CHECKED_COMPILE_DEFS}>
	$<$<CONFIG:profile>:${BLASTTOOLS_SLN_PROFILE_COMPILE_DEFS}>
	$<$<CONFIG:release>:${BLASTTOOLS_SLN_RELEASE_COMPILE_DEFS}>
)

