#
# Build BlastUnitTests PS4
#

SET(BLASTUNITTESTS_PLATFORM_COMMON_FILES
)

SET(BLASTUNITTESTS_PLATFORM_INCLUDES
)

SET(BLASTUNITTESTS_COMPILE_DEFS
	# Common to all configurations
	${BLASTTESTS_SLN_COMPILE_DEFS}
	
	$<$<CONFIG:debug>:${BLASTTESTS_SLN_DEBUG_COMPILE_DEFS}>
	$<$<CONFIG:checked>:${BLASTTESTS_SLN_CHECKED_COMPILE_DEFS}>
	$<$<CONFIG:profile>:${BLASTTESTS_SLN_PROFILE_COMPILE_DEFS}>
	$<$<CONFIG:release>:${BLASTTESTS_SLN_RELEASE_COMPILE_DEFS}>
)

SET(BLASTUNITTESTS_PLATFORM_LINKED_LIBS
    -lpthread
    -lm
)
